from datetime import datetime
from typing import Optional

from odmantic import Field, Model, EmbeddedModel


class Card(EmbeddedModel):
    bin: Optional[str] = Field(description="The BIN/INN of the card. This is the usually the first 6 digits of the "
                                           "payment card.")
    last_four: Optional[str] = Field(description="Last 4 digits of the payment card")
    auth_code: str = Field(description="The authorization code used to match the payment with the bank clearing "
                                       "process")
    scheme: str = Field(description="The scheme of this card. For example: MASTERCARD, VISA, AMEX, etc")


class BankTransaction(Model):
    transaction_id: str = Field(description="Unique transaction ID generated by bank. Repetead ID's will not be "
                                            "accepted")
    bank_id: Optional[str] = Field(description="Bank unique identifier on Cherx. Doesn't need to be provided as we will"
                                               "get it with your authentication. Different bank_id from authentication"
                                               "will not be accepted")
    card: Card = Field(description="Details about the payment card")
    customer_id: str = Field(description="Unique customer identifier at the bank")
    transaction_date: datetime = Field(description="The full date time (RFC3339), at second resolution or better. "
                                                   "This must be the transaction authorization date - not the "
                                                   "settlement date.")
    amount: float
    isRefund: bool = Field(False, description="Is this transaction a refund of a previous transaction")
    isReversal: bool = Field(False, description="Is this transaction a reversal of a previous transaction")
    linkedTransactionId: str = Field(..., description="If this transaction is linked to a previous bank transaction you"
                                                      " have sent then the bankTransactionId used then can be "
                                                      "populated here.")
