name: deploy-aws-lambda

on:
  push:
    branches:
      - continuous_deployment
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: pip install -r requirements.txt --target ./packages
    - name: Zip dependencies
      run: cd packages && zip -r ../deploy.zip .
    - name: Zip source
      run: src/ && zip -g -r ../deploy.zip